@Restaurants.API_HostAddress = https://localhost:7163

GET {{Restaurants.API_HostAddress}}/api/restaurants

###



@routeId=2
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{routeId}}

###



PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1002
Content-Type: application/json

{
  "Name": "Spicy delights",
  "Description": "anananan",
  "HasDelivery": true
}

###



@id=1007
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
    "Name": "Sphatteeiii",
    "Description": "THe classic",
    "Price": 5,
    "KiloCalories": 2
}

###

@restaurantId=1
@dishId=2
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

###
