@Restaurants.API_HostAddress = https://localhost:7163
@token = CfDJ8CjnroVz0RtDnKXVs0AaCZW7z2UEG5eTQurABGRWZTahDyGXsL_UwK7GOcy8AW90DaXncdQ9KoLR1EHjFG1GtBpw3xmCBC83iSFrrok7gJl9auB_4HE47E_EvifBrGfPr0OFUdCT8nO6CYz5ZRv7DGGCQVxfEQiw4e3Vh7akYk_GMPTWIgbxqKb_ynhUJjruER6w_TAN3KuCeeUXirpXYZ8TVLc9OkGgCY9U9JDW2TVHcmQ6SRPWux806smosii2e9t3FNULcwSYcnt2nRR91PJktc6pFXn8smiZlTXg-kN33JhNsXtCXfZvdDc3y4TEeRO4IrGFSkVTWc5OJKjIExIUys0wGz7uXH8ZcAHIrcI7X5h__lJZhuldVJCkXecDVWCpKWXJ9u3uUc3GCkxDSo9NSCzfx0Fh89sPAYCqT541RSEnl-KEDkuM5YPJLD97fbQDLsN5rmGXKO6AMbv8OKlWkUBCCZW_9hhOJVv8j-6e09PTPlqksuvSj5J3tSHufomNWVINaKmNOqUiexIwBjtMkVSxj9xXDArvSZ6xYca2SAN9L9W1prz-q0DzrVRmYzPX9-gJHM-JLGsbV9XTdJA9Z8ZJ4rw6-rdlNiCB1SHuWZzsOUHe4zezVe597Gc2Yizs5prQRLsV9NGGM_5gKsZJE3VfrBaGcoUMUQ2hX5swQg1dJZfo-Z2pWJYMYttsPqyZs_Tyk-zeZHJZDBYiQWL-OevZqLZi_uncYpLn3-hS7WOfFsAFbfX9G-dYbURYavrn6VMUYkpY2phcbaHa-4pwMjMTOordSxJQ4aEzCtzy
GET {{Restaurants.API_HostAddress}}/api/restaurants
###



@routeId=2
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{routeId}}
Authorization: Bearer {{token}}
###



PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1002
Content-Type: application/json

{
  "Name": "Spicy delights",
  "Description": "anananan",
  "HasDelivery": true
}

###



@id=1007
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
    "Name": "Sphatteeiii",
    "Description": "THe classic",
    "Price": 5,
    "KiloCalories": 2
}

###

@restaurantId=1
@dishId=2
GET {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes/{{dishId}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

###


POST {{Restaurants.API_HostAddress}}/api/user/register
Content-Type: application/json
{
    "email": "user@test.com",
    "password": "Abols1234!"
}
###

POST {{Restaurants.API_HostAddress}}/api/user/login
Content-Type: application/json
{
    "email": "admin@test.com",
    "password": "Abols1234!"
}
###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
   "Name": "Spicy delights",
  "Description": "anananan",
  "HasDelivery": true
}

###
